In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

In [6]:
df = pd.read_csv("titanic.csv")
print("Dataset loaded successfully")
print("Dataframe shape:", df.shape)
df.head()

Dataset loaded successfully
Dataframe shape: (891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
df.isnull().head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False

In [14]:
print("Missing values per column")
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [18]:
print("Missing values percentage")
(df.isnull().sum() / len(df)) * 100

Missing values percentage

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [26]:
df.describe()
# initial statistics

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

print("Dataframe column-wise information")
df.info()

In [43]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [47]:
# Variable descriptions
var_desc = {
    "PassengerID": "Unique ID for every passenger",
    "Survived" : "Survival Status",
    'Pclass' : 'Passenger Ticket CLass',
    'Sex' : 'Gender of the passenger',
    'Age' : 'Age of the passenger in years',
    'SibSp' : 'No. of siblings or spouses aboard',
    'Parch' : 'No. of parents or children aboard',
    'Ticket' : 'Ticket number',
    'Fare' : 'Passenger Fare paid',
    'Cabin' : 'Cabin number',
    'Embarked' : 'Port where embarded'
}

for item, val in var_desc.items():
    print(f"{item:} -> {val}")

PassengerID -> Unique ID for every passenger
Survived -> Survival Status
Pclass -> Passenger Ticket CLass
Sex -> Gender of the passenger
Age -> Age of the passenger in years
SibSp -> No. of siblings or spouses aboard
Parch -> No. of parents or children aboard
Ticket -> Ticket number
Fare -> Passenger Fare paid
Cabin -> Cabin number
Embarked -> Port where embarded

# Data Formatting and Normalization

In [50]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

## Filling the missing values

In [61]:
# Filling blank Age column values with medians
df['Age'].fillna(df['Age'].median(), inplace=True)

# Filling the Embarked column blank values with mode (most frequent)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_17696\1989779856.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [67]:
# Dropping the Cabin column since it has too many missing value rows (around 77 %)
df.drop(columns = ['Cabin'], inplace=True)

In [71]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [79]:
### Normalizing the numeric columns with min max scaling
scaler = MinMaxScaler()
# Selecting the numeric data variables
numeric_cols = ['Age', 'SibSp', 'Parch', 'Fare']
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

print("Normalized numeric columns")
df[numeric_cols].head()

Normalized numeric columns

        Age  SibSp  Parch      Fare
0  0.271174  0.125    0.0  0.014151
1  0.472229  0.125    0.0  0.139136
2  0.321438  0.000    0.0  0.015469
3  0.434531  0.125    0.0  0.103644
4  0.434531  0.000    0.0  0.015713

### Categorical Variables to Quantitative conversion

In [90]:
le = LabelEncoder()
df['Sex_Encoded'] = le.fit_transform(df['Sex'])
df['Embarked_Encoded'] = le.fit_transform(df['Embarked'])
print('Original vs Label Encoded')
print(df[['Sex', 'Sex_Encoded', 'Embarked', 'Embarked_Encoded']].head())

Original vs Label Encoded
      Sex  Sex_Encoded Embarked  Embarked_Encoded
0    male            1        S                 2
1  female            0        C                 0
2  female            0        S                 2
3  female            0        S                 2
4    male            1        S                 2

In [92]:
# Final cleaned dataset
print("Final Dataset Shape:", df.shape)
df.head()

Final Dataset Shape: (891, 13)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Sex_Encoded,Embarked_Encoded
0,1,0,3,"Braund, Mr. Owen Harris",male,0.271174,0.125,0.0,A/5 21171,0.014151,S,1,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.472229,0.125,0.0,PC 17599,0.139136,C,0,0
2,3,1,3,"Heikkinen, Miss. Laina",female,0.321438,0.000,0.0,STON/O2. 3101282,0.015469,S,0,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.434531,0.125,0.0,113803,0.103644,S,0,2
4,5,0,3,"Allen, Mr. William Henry",male,0.434531,0.000,0.0,373450,0.015713,S,1,2